### ISSUE TITLE
Game lobby issues

### ISSUE THREAD

**Issue by pjindras** [Ayman-Isam/HungerGames#9]
Hi, I wanted to go to your discord, but the link on spigot expired.

The problem is, when I created 3 arenas using the tutorial there on wiki, I made a config for each of the worlds (arenas)

My config for each of them: https://mclo.gs/9G08pfa

I made a world lobby with the lobby. When someone joins this world, he isn't assigned to the game directly, there is also this error message in chat. 
![image](https://github.com/user-attachments/assets/f27fefb5-aa43-4440-b0b0-bd684369d14a)

But after typing /hg map map name, it works.

Please help me how to set up the game lobby correctly?

Thank you!

Edit: MC version 1.20.4 using Purpur MC. Using Velocity but lobby and all maps are on the same server.

**Comment by Ayman-Isam** [comment]
Firstly, I checked the discord link on spigot and it worked for me and I specifically set the link to never expire, however, I'll add it here anyways https://discord.gg/qcRfPHnZtp.

If you want to work with the lobby, first can you confirm that you are running the latest version of the plugin. If so this is how I did my multi lobby setup, please respond with any other questions you have

Minecraft servers always require a world called "world" (for some reason) and there are a lot of special conditions for that world. For that world, I have the lobby with basically a void world with a barrier block box. I use that as a temporary world for restoring world but you don't have to do that. But what you should do is have worlds other than the world called world, for example I have station, seacliff, moon etc. These maps are the real maps that the game is played on. 

My main map is seacliff so what I do is in the config.yml is set the default-world parameter to seacliff and this makes it so that players get teleported to seacliff first.

If you have any other questions please let me know

**Comment by pjindras** [comment]
Hi, yes I am using latest plugin version.

I have many worlds, for each map I have world and I have lobby world for a lobby.
I also have a world world.

![image](https://github.com/user-attachments/assets/3d334424-5276-480c-880b-6ff555155485)

But the problem is, that I cannot join lobby after joining the server and after leaving it, it teleports me to world world not to lobby. I have a video.

https://www.youtube.com/watch?v=xjccUqgTxfQ

**Comment by pjindras** [comment]
+ after /hg leave (in the moment when video ended) the player remains on the game map, so I must have configured the lobby somehow incorrectly, but I dont know how to configure it better

**Comment by Ayman-Isam** [comment]
The way this plugin works currently, the lobby world should be called world, it doesn't support changing the name for the lobby but I'll add that in the next update. Also doing /hg leave also doesn't send players back to the lobby but to the top of the world at the spawnpoint. I'll add the features in the next update

**Comment by Ayman-Isam** [comment]
The latest version of the plugin now sends players back to the lobby after each game and then players can choose which world to join, the issue is now closed
